# Usa una imagen base de Node.js
FROM node:18

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de tu proyecto
COPY package*.json ./
COPY . .

# Instala las dependencias
RUN npm install --production

# Construye el proyecto
RUN npm run build

# Expone el puerto de la aplicación
EXPOSE 3000

# Comando para iniciar el servidor en producción
CMD ["npm", "run", "start"]
