FROM quay.io/keycloak/keycloak:latest

# Configure a database vendor
ENV KEYCLOAK_FEATURES=token-exchange
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://database-host:5432/keycloak
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=keycloakpassword

WORKDIR /opt/keycloak

# Ensure correct permissions
USER root
RUN chown -R keycloak:keycloak /opt/keycloak
RUN chmod +x /opt/keycloak/bin/kc.sh

# Switch back to the keycloak user
USER keycloak

RUN /opt/keycloak/bin/kc.sh build

# Expose necessary ports
EXPOSE 8080

# Start Keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers=xforwarded", "--hostname=https://build-keycloak-162127822228.us-central1.run.app", "--http-enabled=true", "--optimized"]

