FROM node:22-alpine

WORKDIR /app

COPY . .

RUN npm install

# IMPORTANTE: aseguramos que el build vea las variables definidas por Cloud Run
ARG NUXT_PUBLIC_GEOSERVER_BASEURL
ARG NUXT_PUBLIC_GEONODE_BASEURL
ARG NUXT_PUBLIC_GEONODE_FORCE_SCRIPT_NAME
ARG NUXT_PUBLIC_GEONODE_ADMIN_PATH

ENV NUXT_PUBLIC_GEOSERVER_BASEURL=$NUXT_PUBLIC_GEOSERVER_BASEURL
ENV NUXT_PUBLIC_GEONODE_BASEURL=$NUXT_PUBLIC_GEONODE_BASEURL
ENV NUXT_PUBLIC_GEONODE_FORCE_SCRIPT_NAME=$NUXT_PUBLIC_GEONODE_FORCE_SCRIPT_NAME
ENV NUXT_PUBLIC_GEONODE_ADMIN_PATH=$NUXT_PUBLIC_GEONODE_ADMIN_PATH

RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=3000
ENV NODE_ENV=production

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
