FROM us-central1-docker.pkg.dev/maptail/cloud-run-source-deploy/geonode-nuxt-client/build-keycloak:latest

# Enable health and metrics support
# ENV KC_HEALTH_ENABLED=true
# ENV KC_METRICS_ENABLED=true
# Configure a database vendor
# ENV KC_DB=postgres
# ENV KC_DB_URL=jdbc:postgresql://database-host:5432/keycloak
# ENV KC_DB_USERNAME=keycloak
# ENV KC_DB_PASSWORD=keycloakpassword
# ENV KC_HOSTNAME_URL=localhost
# ENV KEYCLOAK_FEATURES=token-exchange
# ENV KEYCLOAK_FEATURES=token-exchange

WORKDIR /opt/keycloak

# Expose the necessary ports
EXPOSE 8080 8443
# EXPOSE 8080

# Start Keycloak in development mode
# ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers=forwarded", "--features=token-exchange", "--hostname=https://run-keycloak-162127822228.us-central1.run.app", "--http-enabled=true", "--optimized"]
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--proxy-headers=xforwarded", "--hostname=https://run-keycloak-162127822228.us-central1.run.app", "--http-enabled=true", ]
