FROM ubuntu:24.04

# Establecer el entorno no interactivo
ENV DEBIAN_FRONTEND=noninteractive

# Actualizar e instalar dependencias
RUN apt-get update && apt-get install -y \
    flex bison libfcgi-dev libxml2 libxml2-dev curl openssl autoconf apache2 \
    python3-software-properties subversion libmozjs185-dev python3-dev build-essential \
    libxslt1-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar dependencias adicionales necesarias para ZOO-Project
RUN apt-get install -y \
    software-properties-common \
    && add-apt-repository ppa:ubuntugis/ppa \
    && apt-get update && apt-get install -y \
    libgdal1-dev

# Clonar ZOO-Project desde GitHub
RUN git clone https://github.com/ZOO-Project/ZOO-Project.git /zoo-project

# Instalar la librería cgic
WORKDIR /zoo-project/thirds/cgic206/
RUN make

# Configurar ZOO-Project
WORKDIR /zoo-project/zoo-kernel/
RUN autoconf && ./configure --with-js --with-python && make && make install

# Copiar archivos necesarios a cgi-bin
RUN cp /zoo-project/zoo-kernel/main.cfg /usr/lib/cgi-bin && \
    cp /zoo-project/zoo-kernel/zoo_loader.cgi /usr/lib/cgi-bin

# Configuración de Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf && \
    a2enmod cgi && \
    service apache2 restart

# Exponer el puerto
EXPOSE 8080

# Comando para ejecutar el contenedor
CMD ["apache2ctl", "-D", "FOREGROUND"]
